"""agent_sessions/messages/citations/runs/feedback (CR-DB-007)

Revision ID: 99ce6239f9b0
Revises: b7d3e5f10a22
Create Date: 2026-08-27 16:33:44.191583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99ce6239f9b0'
down_revision: Union[str, Sequence[str], None] = 'b7d3e5f10a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('closed', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_sessions_scope', 'agent_sessions', ['scope'], unique=False)
    op.create_index('ix_agent_sessions_user_active', 'agent_sessions', ['user_id', 'last_active_at'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('answer_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_agent_messages_session_seq')
    )
    op.create_index('ix_agent_messages_session_seq', 'agent_messages', ['session_id', 'seq'], unique=False)
    op.create_table('agent_citations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('source_ref', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['doc_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['agent_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_citations_message_ord', 'agent_citations', ['message_id', 'ord'], unique=False)
    op.create_table('agent_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['agent_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_agent_feedback_message_user')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('route', sa.String(length=10), nullable=False),
    sa.Column('answer_status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('model_id', sa.String(length=60), nullable=True),
    sa.Column('rule_hash', sa.String(length=64), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=True),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regenerated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('prompt_sent', sa.Text(), nullable=True),
    sa.Column('raw_answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['agent_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_created', 'agent_runs', ['created_at'], unique=False)
    op.create_index('ix_agent_runs_scope_created', 'agent_runs', ['scope', 'created_at'], unique=False)
    op.create_index('ix_agent_runs_status', 'agent_runs', ['answer_status'], unique=False)
    op.create_index('ix_agent_runs_user_created', 'agent_runs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_runs_user_created', table_name='agent_runs')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_index('ix_agent_runs_scope_created', table_name='agent_runs')
    op.drop_index('ix_agent_runs_created', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('agent_feedback')
    op.drop_index('ix_agent_citations_message_ord', table_name='agent_citations')
    op.drop_table('agent_citations')
    op.drop_index('ix_agent_messages_session_seq', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('ix_agent_sessions_user_active', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_scope', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
