"""SF-TD5 initial schema: 10 tables

Revision ID: ab45607508d8
Revises: 
Create Date: 2026-08-25 01:18:47.985691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab45607508d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('eq_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='normal', nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('uptime', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_maintenance', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eq_id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('model_type', sa.String(length=30), nullable=False),
    sa.Column('rmse', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('r2', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('mape', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('train_samples', sa.Integer(), nullable=True),
    sa.Column('artifact_path', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('primary_material', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='viewer', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('sn_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('ag_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('cu_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pb_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('time_min', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id')
    )
    op.create_index('idx_lots_date', 'lots', [sa.literal_column('date DESC')], unique=False)
    op.create_index('idx_lots_status', 'lots', ['status'], unique=False)
    op.create_index('idx_lots_supplier', 'lots', ['supplier_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('components',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sn', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('ag', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('cu', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pb', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('sn_deviation', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('ag_deviation', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('cu_deviation', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('analysis_method', sa.String(length=20), server_default='XRF', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(length=30), nullable=False),
    sa.Column('predicted_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('customer', sa.String(length=100), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=10), server_default='kg', nullable=False),
    sa.Column('shipped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_table('quality')
    op.drop_table('components')
    op.drop_table('alerts')
    op.drop_index('idx_lots_supplier', table_name='lots')
    op.drop_index('idx_lots_status', table_name='lots')
    op.drop_index('idx_lots_date', table_name='lots')
    op.drop_table('lots')
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('ml_models')
    op.drop_table('equipment')
    # ### end Alembic commands ###
