"""CR-DB-001: add 8 tables for 44-screen coverage

Revision ID: bd14233e77af
Revises: ab45607508d8
Create Date: 2026-08-25 09:14:24.981304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd14233e77af'
down_revision: Union[str, Sequence[str], None] = 'ab45607508d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_targets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kpi_key', sa.String(length=30), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_key', 'period', name='uq_kpi_targets_key_period')
    )
    op.create_index('idx_kpi_targets_period', 'kpi_targets', ['period'], unique=False)
    op.create_table('master_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_code', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code', 'code', 'version', name='uq_master_codes_group_code_version')
    )
    op.create_index('idx_master_codes_group', 'master_codes', ['group_code'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('channel', sa.String(length=10), server_default='system', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'channel', name='uq_notification_rules_event_channel')
    )
    op.create_table('process_conditions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('temp_min', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('temp_max', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('time_min', sa.Integer(), nullable=False),
    sa.Column('time_max', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code', 'version', name='uq_process_conditions_product_version')
    )
    op.create_index('idx_process_conditions_product', 'process_conditions', ['product_code'], unique=False)
    op.create_table('condition_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['condition_id'], ['process_conditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_condition_history_created', 'condition_history', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('receipt_no', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('material', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=10), server_default='kg', nullable=False),
    sa.Column('status', sa.String(length=15), server_default='inspecting', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no')
    )
    op.create_index('idx_receipts_date', 'receipts', [sa.literal_column('date DESC')], unique=False)
    op.create_index('idx_receipts_status', 'receipts', ['status'], unique=False)
    op.create_index('idx_receipts_supplier', 'receipts', ['supplier_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('value_type', sa.String(length=10), server_default='string', nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('claims',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('claim_no', sa.String(length=20), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('customer', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='open', nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_no')
    )
    op.create_index('idx_claims_lot', 'claims', ['lot_id'], unique=False)
    op.create_index('idx_claims_status', 'claims', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_claims_status', table_name='claims')
    op.drop_index('idx_claims_lot', table_name='claims')
    op.drop_table('claims')
    op.drop_table('system_settings')
    op.drop_index('idx_receipts_supplier', table_name='receipts')
    op.drop_index('idx_receipts_status', table_name='receipts')
    op.drop_index('idx_receipts_date', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index('idx_condition_history_created', table_name='condition_history')
    op.drop_table('condition_history')
    op.drop_index('idx_process_conditions_product', table_name='process_conditions')
    op.drop_table('process_conditions')
    op.drop_table('notification_rules')
    op.drop_index('idx_master_codes_group', table_name='master_codes')
    op.drop_table('master_codes')
    op.drop_index('idx_kpi_targets_period', table_name='kpi_targets')
    op.drop_table('kpi_targets')
    # ### end Alembic commands ###
