"""CR-DB-003: receipts composition + kpi actual_updated_at

Revision ID: ce41da66a81b
Revises: 2609e28f94d3
Create Date: 2026-08-25 10:12:38.115072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce41da66a81b'
down_revision: Union[str, Sequence[str], None] = '2609e28f94d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_targets', sa.Column('actual_updated_at', sa.DateTime(), nullable=True))
    op.add_column('receipts', sa.Column('sn_pct', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('receipts', sa.Column('ag_pct', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('receipts', sa.Column('cu_pct', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('receipts', sa.Column('pb_pct', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('receipts', sa.Column('analysis_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'analysis_method')
    op.drop_column('receipts', 'pb_pct')
    op.drop_column('receipts', 'cu_pct')
    op.drop_column('receipts', 'ag_pct')
    op.drop_column('receipts', 'sn_pct')
    op.drop_column('kpi_targets', 'actual_updated_at')
    # ### end Alembic commands ###
