"""doc_sources/doc_chunks (CR-DB-007 partial, no vector cols)

`agent-architecture.md` §6.7 의 두 테이블을 **벡터 3컬럼 없이** 만든다.

§6.7 은 `embedding vector(N)` · `embed_model` · `embed_dim` 을 NOT NULL 로
규정하지만, 같은 문서 §8 미결항목 2번이 임베딩 모델과 차원을 **미정**으로 두고
"`vector(N)` 의 N 은 DDL 에 고정되므로 `AGENT_EMBED_MODEL` 을 확정한 뒤
마이그레이션을 생성해야 한다" 고 명시했다. 차원을 지금 지어내면 모델 확정 시
컬럼 타입 변경 + 전량 재색인이므로, 여기서는 **청크 본문까지만** 적재한다.

따라서 이 마이그레이션 뒤에도 검색은 동작하지 않는다.
`doc_sources.index_status` 는 `pending` 으로 남고 `GET /agents/health` 의
`index_ready` 는 false 다 (§3.5 D3 — 색인이 비어 있으면 비어 있다고 말한다).

후속 마이그레이션이 할 일:
  1. `CREATE EXTENSION vector`
  2. `embedding vector(N)` · `embed_model` · `embed_dim` 추가
  3. HNSW (vector_cosine_ops, m=16, ef_construction=64) + (embed_model) 인덱스
  4. 전량 임베딩 후 `index_status='indexed'`

Revision ID: fa92a1c0504e
Revises: ce41da66a81b
Create Date: 2026-08-27 12:18:48.133365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa92a1c0504e'
down_revision: Union[str, Sequence[str], None] = 'ce41da66a81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_key', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=20), server_default='common', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('index_status', sa.String(length=15), server_default='pending', nullable=False),
    sa.Column('index_error', sa.String(length=300), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_key', name='uq_doc_sources_type_key')
    )
    op.create_table('doc_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['doc_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'chunk_index', name='uq_doc_chunks_source_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_chunks')
    op.drop_table('doc_sources')
    # ### end Alembic commands ###
